name: deploy-book

# Trigger the workflow on push to main branch and PRs
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

# This job installs dependencies, builds the book, and deploys the html
jobs:
  build-and-deploy-site:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Build the site
    - name: Build the site
      run: make html

    # Deploy the book's html
    - name: GitHub Pages action
      if: github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: _build/html
        full_commit_message: "GitHub action book deploy"
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        external_repository: ocean-transport/ocean-transport.github.io
        publish_branch: master
